from django.shortcuts import render

# Create your views here.
def home(request):
    context = {
        'title': 'Welcome to My Website',
        'content': 'This is a dynamic content generated by Django!',
    }
    return render(request, 'home.html', context)
